Runtime check
MissouriMRR/SUAS-2023 pull request #110
Opened 2023-04-12 00:38 UTC by DJDMVP

changes to flight manager to check time and if it reaches 28 minutes returns the drone to home

2023-04-14 18:52 UTC, fallscameron01 commented
Not passing `pylint`. See report below:
```
- hook id: pylint
- exit code: 30

************* Module flight.flight
flight/flight.py:62:0: C0301: Line too long (101/100) (line-too-long)
flight/flight.py:242:0: C0301: Line too long (148/100) (line-too-long)
flight/flight.py:253:0: C0301: Line too long (111/100) (line-too-long)
flight/flight.py:25:4: W0107: Unnecessary pass statement (unnecessary-pass)
flight/flight.py:28:0: R0903: Too few public methods (1/2) (too-few-public-methods)
flight/flight.py:145:8: W0707: Consider explicitly re-raising using 'except Exception as exc' and 'raise DroneNotFoundError() from exc' (raise-missing-from)
flight/flight.py:169:11: W0703: Catching too general exception Exception (broad-except)
flight/flight.py:185:8: W0702: No exception type(s) specified (bare-except)
flight/flight.py:213:4: W0702: No exception type(s) specified (bare-except)
flight/flight.py:240:0: R1711: Useless return at end of function or method (useless-return)
flight/flight.py:7:0: C0411: standard import "from multiprocessing import Queue" should be placed before "from mavsdk import System" (wrong-import-order)
flight/flight.py:14:0: C0411: standard import "import time" should be placed before "from mavsdk import System" (wrong-import-order)
************* Module flight_manager
flight_manager.py:97:8: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)
flight_manager.py:99:34: E1101: Instance of 'BaseManager' has no 'Communication' member (no-member)
flight_manager.py:115:8: W1203: Use lazy % formatting in logging functions (logging-fstring-interpolation)
flight_manager.py:116:8: W1203: Use lazy % formatting in logging functions (logging-fstring-interpolation)
flight_manager.py:13:0: C0411: standard import "import time" should be placed before "from logger import init_logger, worker_configurer" (wrong-import-order)
flight_manager.py:13:0: W0611: Unused import time (unused-import)

-----------------------------------
Your code has been rated at 8.66/10
```

2023-04-25 23:54 UTC, cjhr95 requested changes
Some labeling stuff

2023-04-25 23:54 UTC, cjhr95 commented on flight/flight.py
> +        time.sleep(60)
Please label the significance of these two values with a comment

2023-04-25 23:54 UTC, cjhr95 commented on flight/flight.py
> +    None
If it only returns None, this section of the docstring isn't required

2023-04-25 23:54 UTC, cjhr95 commented on flight_manager.py
> +                elif time_process.is_alive() is not True:
Could you just do `elif not time_process.is_alive():`

2023-04-26 00:41 UTC, cjhr95 requested changes
Fix the comment please :)

2023-04-26 00:41 UTC, cjhr95 commented on flight/flight.py
> +    # 1680 is seconds in seconds and that signals that we are almost out of time
I'm assuming this is supposed to be "1680 is 28 minutes in seconds"

2023-04-26 00:48 UTC, cjhr95 approved these changes
Go for it, boss

2023-04-26 00:49 UTC, merged