Feature/flyover vision pipeline
MissouriMRR/SUAS-2023 pull request #112
Opened 2023-04-14 00:13 UTC by EnderDude67

Closes #17 

- Adds `flyover_vision_pipeline.py`
  - `flyover_pipeline()` runs the vision code and saves the output to a file when completed (this should be changed later)
- Adds `vision/pipeline/emergent_object.py`
  - `find_humanoids()` runs the emergent object code and returns all bounding boxes of humanoids in an image
- Adds `vision/pipeline/standard_object.py`
  - `find_standard_objects()` runs the standard object detection/classification code and returns all shapes in an image
- Adds `vision/pipeline/pipeline_utils.py`
  - Includes functions used in the standard and emergent object sections of the pipeline and in the flyover pipeline

2023-04-14 04:08 UTC, fallscameron01 requested changes
Few changes. Main one is that `continue` statements can be avoided.

2023-04-14 04:08 UTC, fallscameron01 commented on flyover_vision_pipeline.py
> +        )
You could create a `TypedDict` type for this for clarity

2023-04-14 04:08 UTC, fallscameron01 commented on vision/common/constants.py
> +JSON_PATH: str = ""
Should these be blank? If so, I'm not sure what the point of them is.

2023-04-14 04:08 UTC, fallscameron01 commented on vision/pipeline/emergent_object.py
> +        found_humanoids.append(emergent)
Alternative would be to just remove the `not` from the if statement and move the `found_humanoids.append(emergent)` to where the `continue` is

2023-04-14 04:08 UTC, fallscameron01 commented on vision/pipeline/pipeline_utils.py
> +        return str(file.read) == "True"
What is the type of `file.read`? If it's already a bool, you can just return that.

2023-04-14 04:08 UTC, fallscameron01 commented on vision/pipeline/standard_object.py
> +            found_odlcs.append(shape)
Similar thing here about `continue`s. You could just have the `found_odlcs.append(shape)` under an if statement with the checks that you have. `continue`s aren't really necessary and just make the code harder to follow

2023-04-14 04:08 UTC, fallscameron01 commented on vision/pipeline/standard_object.py
> +        odlc_dict[str(i)] = {"latitude": average_coord[0], "longitude": average_coord[1]}
Whole buncha type hints. `i`, `bottle`, `shape`, `coords_array`, `average_coord`

2023-04-14 15:18 UTC, EnderDude67 commented on flyover_vision_pipeline.py
> +        )
By my understanding, this cannot be a `TypedDict` because the keys are image paths and not fixed values

2023-04-14 15:49 UTC, EnderDude67 commented on vision/pipeline/pipeline_utils.py
> +        return str(file.read) == "True"
For the moment, it is just a txt file with the word "True" or "False" in it. We can (and should) change it later.

2023-04-14 17:29 UTC, fallscameron01 requested changes
Couple of things before I do another thorough review:
- Make sure you are passing `pylint`. Ran it and you were getting this issue:
```
vision/pipeline/pipeline_utils.py:11:0: C0411: standard import "from typing import TypeAlias" should be placed
 before "import vision.common.constants as consts" (wrong-import-order)
```
- `flyover_vision_pipeline.py` should be moved to the base of the `vision` folder
- In that same vein, could you update `vision/README.md` to give a brief summary of how to use the pipeline.

2023-04-15 19:05 UTC, fallscameron01 requested changes
A few changes, mostly with regards to docstring issues.

2023-04-15 19:05 UTC, fallscameron01 commented on vision/pipeline/emergent_object.py
> +"""Functions that run emergent object detection to find human(oid)s in an image"""
Might want to rename this file since there is already an `emergent_object.py` under vision > emergent_object. That's just to ensure we don't have two modules with the same name.

2023-04-15 19:05 UTC, fallscameron01 commented on vision/pipeline/pipeline_utils.py
> +        The python dict version of the data from the given json file.
Return type in docstring doesn't match type hint

2023-04-15 19:05 UTC, fallscameron01 commented on vision/pipeline/pipeline_utils.py
> +FolderParameters: TypeAlias = dict[str, consts.CameraParameters]
Not sure this needs to be a type alias. Abstracting a bit too much considering it's just a dictionary.

2023-04-15 19:05 UTC, fallscameron01 commented on vision/pipeline/standard_object.py
> +        The details of how and where the photo was taken
Parameters in docstring not correct

2023-04-15 19:05 UTC, fallscameron01 commented on vision/pipeline/standard_object.py
> +        The path for the image the bounding box is from
Parameters in docstring not correct

2023-04-15 19:05 UTC, fallscameron01 commented on vision/pipeline/emergent_object.py
> +        The model which is being used for object detection/classification
Put parameters in same order in docstring and function definition.

2023-04-15 19:05 UTC, fallscameron01 commented on vision/pipeline/standard_object.py
> +        The list of sightings of each object, matched to bottles
Need extra newline between parameters and returns

2023-04-15 19:05 UTC, fallscameron01 commented on vision/pipeline/standard_object.py
> +        The list of sightings of each object, matched to bottles
Need parameter name in docstring

2023-04-16 02:03 UTC, fallscameron01 approved these changes
Nice work, looks ready to merge.

2023-04-16 03:20 UTC, merged