Std odlc classification/filtering tweaks & odlc_colors.py bugfix
MissouriMRR/SUAS-2023 pull request #123
Opened 2023-04-21 00:33 UTC by OrangePear13

Some small changes to odlc_classify_shape.py that should reduce the number of false positive std odlc detections.

A small bugfix in odlc_colors.py.

2023-04-21 00:55 UTC, fallscameron01 requested changes
Small change

2023-04-21 00:55 UTC, fallscameron01 commented on vision/standard_object/odlc_classify_shape.py
> +    return curr
The return variable is `curr`

2023-04-25 23:50 UTC, fallscameron01 approved these changes

2023-04-26 01:36 UTC, OrangePear13 commented
There was another update to develop after I merged it into this branch, so it made me merge develop in again.

2023-04-26 02:50 UTC, fallscameron01 approved these changes

2023-04-26 03:56 UTC, merged