README's V 1.0
MissouriMRR/SUAS-2023 pull request #125
Opened 2023-04-25 23:36 UTC by Lmyszka4

2023-04-25 23:55 UTC, fallscameron01 requested changes

2023-04-25 23:55 UTC, fallscameron01 commented on flight/README.md
> +This is the repository that holds the flight movement code. The code here allows the drone to complete all of its required functions during competition flight. Every function for connection and takeo
This is folder

2023-04-26 00:07 UTC, cjhr95 requested changes
More professional

2023-04-26 00:07 UTC, cjhr95 commented on flight/README.md
> +Flight contains the functions necessary for initializing the drone's flight and monitoring the statuses of the drone.
Status, singular plz

2023-04-26 00:07 UTC, cjhr95 commented on flight/data/README.md
> +This json file is used for flight data at David Hoffman's plot of land.
Label which file you're referring to specifically with this line

2023-04-26 00:07 UTC, cjhr95 commented on flight/maestro/README.md
> +It has functions for every command that it supports
Provide some examples on what kind of commands are provided

2023-04-26 00:33 UTC, cjhr95 requested changes
One itty-bitty little thing left

2023-04-26 00:33 UTC, cjhr95 commented on flight/test_files/README.md
> +Altitude is set to 100 feet for both.
This isn't entirely true, the testing file have multiple altitudes for different waypoints.

2023-04-26 00:37 UTC, cjhr95 approved these changes
I GUESS this will suffice

2023-04-26 02:50 UTC, fallscameron01 approved these changes
Very nice, looks good

2023-04-27 23:13 UTC, fallscameron01 approved these changes

2023-04-27 23:14 UTC, merged