Rewrite state machine, add new state foundation
MissouriMRR/SUAS-2023 pull request #136
Opened 2023-10-18 00:57 UTC by Ooglely

Replacing the old, broken state machine and flight manager with a new one using multiprocessing and state constructors in order to create a state machine that avoids the problems of circular imports.

2023-10-19 23:09 UTC, cjhr95 requested changes
Lots of missing function docstrings

2023-10-19 23:09 UTC, cjhr95 commented on state_machine/flight_manager.py
> +        """Create and run a state machine in the event loop."""
Missing function docstring

2023-10-19 23:09 UTC, cjhr95 commented on state_machine/flight_manager.py
> +        """Create and run a kill switch in the event loop."""
Also missing full docstring

2023-10-19 23:09 UTC, cjhr95 commented on state_machine/flight_manager.py
> +        Continuously check for whether or not the kill switch has been activated.
Hrrm, interesting. Also missing a function docstring

2023-10-19 23:09 UTC, cjhr95 commented on state_machine/flight_manager.py
> +        """Land the drone and exit the program."""
Another one. Missing function docstring

2023-10-19 23:09 UTC, cjhr95 commented on flight/test_files/state_machine_test.py
> +        _sim (bool): Whether or not to run the state machine in simulation mode.
The sim parameter isn't used in this function. In the flight_manager file, the start_manager() function has no way to distinguish between a simulated flight or a real one.

2023-10-19 23:09 UTC, cjhr95 commented on flight/test_files/state_machine_test.py
> +    """Runs the state machine.
```suggestion
    """
    Runs the state machine.
```

2023-10-19 23:09 UTC, cjhr95 commented on flight/test_files/state_machine_test.py
> +    Args:
```suggestion
    Parameters
    ----------
```

2023-10-19 23:09 UTC, cjhr95 commented on state_machine/drone.py
> +        """Initialize a new Drone object."""
Needs function docstring

2023-10-19 23:09 UTC, cjhr95 commented on state_machine/drone.py
> +    Data can be stored in this class to be shared between states.
Class docstring needs section for class variables and class methods.

2023-10-19 23:09 UTC, cjhr95 commented on state_machine/flight_manager.py
> +from .states import Start
We usually stick to absolute imports, but if changing this yields some wacky errors, let me know.

2023-10-19 23:09 UTC, cjhr95 commented on state_machine/flight_manager.py
> +    def start_manager(self) -> None:
There's no way for this function to initialize a drone with the flight controller's address versus the simulator currently. The sim parameter in the testing files does not make it here.

2023-10-19 23:09 UTC, cjhr95 commented on state_machine/states/impl/land_impl.py
> +from ..state import State
Again, with the imports, if absolute imports destroy the code let me know.

2023-10-19 23:09 UTC, cjhr95 commented on state_machine/states/impl/start_impl.py
> +from ..takeoff import Takeoff
Relative imports? In my code? More likely than you think

2023-10-19 23:09 UTC, cjhr95 commented on state_machine/states/impl/takeoff_impl.py
> +from ..waypoint import Waypoint
I think you get the jist

2023-10-19 23:09 UTC, cjhr95 commented on state_machine/states/impl/waypoint_impl.py
> +from ..waypoint import Waypoint
More relative imports? You guys love these things

2023-10-19 23:09 UTC, cjhr95 commented on state_machine/states/land.py
> +    Attributes:
```suggestion
    Attributes
    ----------
```

2023-10-19 23:09 UTC, cjhr95 commented on state_machine/states/land.py
> +    Methods:
```suggestion
    Methods
    -------
```

2023-10-19 23:09 UTC, cjhr95 commented on state_machine/states/land.py
> +            Returns:
```suggestion
      Returns
      -------
```
Decrease the indent so it matches the other headers

2023-10-19 23:09 UTC, cjhr95 commented on state_machine/states/start.py
> +        -------
Decrease the indentation on this guy as well to match the other headers

2023-10-19 23:09 UTC, cjhr95 commented on state_machine/states/state.py
> +from ..drone import Drone
Relative import yet again

2023-10-20 00:25 UTC, RexBerry commented
I'm not sure switching to absolute imports would be easy given that there some imports from a parent package.

2023-10-24 23:22 UTC, cjhr95 approved these changes

2023-10-24 23:23 UTC, merged