Determine if one boundary is within other boundary
MissouriMRR/SUAS-2023 pull request #149
Opened 2023-10-27 00:59 UTC by brggbr

Issues: #66 and #67 
file location: `SUAS-2023/vision/deskew/within_bounds.py`

`contains_airdrop_boundary(list[list[float]], list[list[float]])`
- Given two lists of points containing x and y coordinates, determines whether any part of either shape created by each list intersects or exists within the other.
- Returns True if any point within the airdrop_boundary is within the image, False otherwise.

`inside_bounds(list[list[float]], list[float])`
- Given one point containing x and y coordinates and a list of points containing x and y coordinates, determines whether the point exists within the boundary created by the list.
- Returns True if the location_point is within the bounds of the shape created by boundary. Returns False otherwise.

2023-10-31 23:00 UTC, cjhr95 requested changes
Just some small formatting stuff

2023-10-31 23:00 UTC, cjhr95 commented on vision/deskew/within_bounds.py
> +        The end point on the line segment.
The notation here would be:
`point1: list[float]`

2023-10-31 23:00 UTC, cjhr95 commented on vision/deskew/within_bounds.py
> +        An Array that contains the x and y coordinates of the point.
Same as above

2023-10-31 23:00 UTC, cjhr95 commented on vision/deskew/within_bounds.py
> +        x and y coordinates.
The nested data structure here would have a similar annotation in the docstring as the function definition:
`line1: [list[list[float]]]`

2023-10-31 23:00 UTC, cjhr95 commented on vision/deskew/within_bounds.py
> +        is made up of x and y coordinates.
Same as above:
`boundary: list[list[float]]`

2023-10-31 23:00 UTC, cjhr95 commented on vision/deskew/within_bounds.py
> +    location_point: [float]
Same as above:
`location_point: list[float]`

2023-10-31 23:00 UTC, cjhr95 commented on vision/deskew/within_bounds.py
> +        A 2D array which contains a number of points where each point
Same formatting as above

2023-10-31 23:00 UTC, cjhr95 commented on vision/deskew/within_bounds.py
> +    val: int = ((point2[1] - point1[1]) * (point3[0] - point2[0])) - (
The type of var is a float. see the mypy error

2023-11-01 01:25 UTC, EnderDude67 requested changes
Looks good! Just a couple small changes just to make things match my own personal preference

2023-11-01 01:25 UTC, eblake003 commented on vision/deskew/within_bounds.py
> +    to_return: bool = False
I would rename `to_return` to something like `is_on_line`. Also, you don't need the `if` statement, you can just write `is_on_line: bool = ((point2[0]`...

2023-11-01 01:25 UTC, eblake003 commented on vision/deskew/within_bounds.py
> +    point1: list[float]
Rename parameters to be more clear about their purpose. I would suggest `line_start`, `line_end`, and `test_point`

2023-11-01 01:25 UTC, eblake003 commented on vision/deskew/within_bounds.py
> +    to_return: bool = False
Same thing here. Rename this to `intersects` or something similar

2023-11-01 01:25 UTC, eblake003 commented on vision/deskew/within_bounds.py
> +def contains_airdrop_boundary(
Consider putting the higher level functions at the top (`contains_airdrop_boundary()`, `inside_bounds()`) to make it immediately apparent what the file is for.

2023-11-01 01:25 UTC, EnderDude67 commented on vision/deskew/within_bounds.py
> +    new_np_boundary: NDArray[Shape["*, *"], Float32] = np.array(boundary)
_Technically_ speaking, the `boundary` variable is a list and not an array. If you want slightly better names, you could use `boundary_list` for the list and `boundary_array` for the numpy array.

2023-11-03 00:43 UTC, EnderDude67 requested changes
Couple small changes

2023-11-03 00:43 UTC, EnderDude67 commented on vision/deskew/within_bounds.py
> +    if ppt_return > 0:
`is_in_bounds` can just be set equal for `ppt_return > 0`

2023-11-03 00:43 UTC, EnderDude67 commented on vision/deskew/within_bounds.py
> +    intersects: bool = False
Move this down to right before the if statements

2023-11-03 00:52 UTC, EnderDude67 approved these changes
Looks good!

2023-11-03 01:06 UTC, cjhr95 approved these changes
Nice work!

2023-11-05 18:04 UTC, merged