Airdrop State
MissouriMRR/SUAS-2023 pull request #156
Opened 2023-12-01 00:54 UTC by DJDMVP

Airdrop state logic implemented. Will drop one bottle at once, will start with the 0th servo and increment for each bottle until the second then go back to the 0th assuming that the bottles got reloaded. Moving to the waypoint state right after.

2024-01-18 19:57 UTC, cjhr95 requested changes
I don't believe the class needs to be duplicated unless there's some wacky stuff with the implementation files...

2024-01-18 19:57 UTC, cjhr95 commented on flight/airdrop.py
Were you unable to import the maestro class from flight/maestro/maestro.py? The Maestro functions look copy/pasted from that file.

2024-01-19 01:52 UTC, cjhr95 approved these changes

2024-01-24 00:21 UTC, Ooglely approved these changes

2024-01-24 00:23 UTC, merged