Correcting bottle dropping order
MissouriMRR/SUAS-2023 pull request #167
Opened 2024-02-23 01:25 UTC by DJDMVP

Changing the servo order for the dropping order of the bottles to maintain center of balance of the drone.

2024-02-29 20:55 UTC, cjhr95 approved these changes, later dismissed

2024-03-01 00:32 UTC, Ooglely requested changes
One small thing

2024-03-01 00:32 UTC, Ooglely commented on state_machine/states/impl/airdrop_impl.py
> +        if (cylinders["C1"])["Loaded"]:
There is nowhere where the bottles are set to unloaded

2024-03-01 01:41 UTC, Ooglely approved these changes
Good now

2024-03-01 01:41 UTC, merged