Implementing land state and refill state
MissouriMRR/SUAS-2023 pull request #173
Opened 2024-03-01 00:55 UTC by DJDMVP

Adding the correct state logic for land state and transitions to land state.

2024-03-01 01:47 UTC, Ooglely submitted a review, later dismissed
The json data isn't typed when it's read but if Connor is good with it I'm good with it

2024-03-01 01:50 UTC, cjhr95 requested changes
Little stuff for a big guy

2024-03-01 01:50 UTC, cjhr95 commented on state_machine/states/impl/airdrop_impl.py
> +        continuerun: bool = False
Snake case plz

2024-03-01 01:50 UTC, cjhr95 commented on state_machine/states/impl/airdrop_impl.py
> +        if continuerun:
`continuerun` needs snake case

2024-03-01 01:50 UTC, cjhr95 commented on state_machine/states/impl/airdrop_impl.py
Edit your logging so it states which bottle number is being dropped

2024-03-06 01:09 UTC, cjhr95 approved these changes
I prefer f-strings, good stuff

2024-03-06 01:11 UTC, merged