Adding error catching for waypoint move to, so the drone won't stop while running waypoints
MissouriMRR/SUAS-2023 pull request #176
Opened 2024-03-06 01:54 UTC by DJDMVP

Catching logging and ignoring the errors from the move_to in waypoint state. To hopefully allow the drone to continue running without stopping.

2024-03-06 02:08 UTC, cjhr95 commented on state_machine/states/impl/waypoint_impl.py
> +                    logging.warning(ActionResult.Result.TIMEOUT)
I sent the logs in the flight channel in the Discord, verify that this is the correct built-in

2024-03-13 17:39 UTC, cjhr95 requested changes
Timeout tests are a little inconclusive, however the core of your implementation seems alright.

2024-03-13 17:39 UTC, cjhr95 commented on state_machine/states/impl/waypoint_impl.py
> +                    await move_to(self.drone.system, lat_deg, lon_deg, curr_altitude, 1.0)
Reduce fast parameter, the drone takes too long at each waypoint

2024-03-21 22:59 UTC, cjhr95 approved these changes

2024-03-22 00:38 UTC, Ooglely approved these changes

2024-03-22 00:52 UTC, merged