ODLC state unit test
MissouriMRR/SUAS-2023 pull request #180
Opened 2024-03-20 00:19 UTC by Ooglely

A unit test for the ODLC state so that we can test its functionality as a standalone state.

2024-03-20 00:20 UTC, Ooglely commented
Waiting on the ability to skip states in the state machine before ready for review

2024-04-02 23:56 UTC, Flamingpuffins commented on flight/test_files/odlc_state_test.py
> +
add docstring

2024-04-03 00:50 UTC, cjhr95 requested changes

2024-04-03 00:50 UTC, cjhr95 commented on state_machine/states/impl/waypoint_impl.py
> +            # removing this because "too many local variables" eww
Change or remove this comment for professionalism's sake.

2024-04-03 00:50 UTC, cjhr95 commented on flight/test_files/odlc_state_test.py
> +    while activated_odlcs != 5:
Change this to a variable or a constant; hard-coded values are usually a no-go

2024-04-10 00:41 UTC, cjhr95 requested changes
Missing a few, quick type hints

2024-04-10 00:41 UTC, cjhr95 commented on flight/test_files/odlc_state_test.py
> +    state_machine = StateMachine(Start(drone, flight_settings), drone, flight_settings)
type hints here

2024-04-10 00:41 UTC, cjhr95 commented on flight/test_files/odlc_state_test.py
> +    activated_odlcs = 0
Needs type hint

2024-04-10 00:41 UTC, cjhr95 commented on flight/test_files/odlc_state_test.py
> +                output_data = json.load(file)
Need a type hint here as well

2024-04-10 01:08 UTC, cjhr95 approved these changes
Nice job kiddos

2024-04-11 15:17 UTC, merged