Standard Object Contour Gathering
MissouriMRR/SUAS-2023 pull request #194
Opened 2024-04-26 00:15 UTC by ths51

closes #154 

**Changes**

- Added vision/standard-object/odlc_contour_detection, which contains a function that detects contours within an image, filters out most of those that are not standard objects, and returns a list of potential standard objects. 

**Additional Notes**

- Function fetchShapeContours() returns a list of all potential standard objects. It is rare, but not impossible, that a standard object is filtered out, and there are still a few non-standard objects that are detected. These should be accounted for by contour classification.

2024-06-09 19:02 UTC, EnderDude67 requested changes
Looks good, just needs a handful of changes.
* Needs more typehints
  * Use premade typealiases from `vision.common.constants`
* "Magic numbers" should go at the top of the file for easier tuning
* This branch should completely replace the old code, so `fetchShapeContours()` should replace `iterate_find_contours()` in `vision/pipeline/standard_pipeline.py`

2024-06-09 19:02 UTC, eblake003 commented on vision/standard_object/odlc_contour_detection.py
> +    # slightly blends blurred and unblurred images of same type, prioritizing blurred images
Consider explaining more why this is necessary or helpful

2024-06-09 19:02 UTC, eblake003 commented on vision/standard_object/odlc_contour_detection.py
> +    _, saturation_thresh = cv2.threshold(img_saturation, (50 if avg_brt > 60 else 125), 255, cv2.THRESH_BINARY)
Break the threshold calculation into a separate line and explain the reasoning behind it

2024-06-09 19:02 UTC, eblake003 commented on vision/standard_object/odlc_contour_detection.py
> +            and (solidity >= 0.75)
All of these constants should go at the top of the file, for example `MIN_SOLIDITY = 0.75`

2024-06-09 19:02 UTC, eblake003 commented on vision/standard_object/odlc_contour_detection.py
> +    if draw_contours:
remove this, it is useful for debugging but is not needed here

2024-06-09 19:02 UTC, eblake003 commented on vision/standard_object/odlc_contour_detection.py
> +    all_contours: list[np.ndarray[np.dtype[np.uint8], np.dtype[np.uint8]]] = []
Use the `Contour` typealias in `vision/common/constants.py`

2024-06-09 19:02 UTC, eblake003 commented on vision/standard_object/odlc_contour_detection.py
> +    img_saturation = cv2.addWeighted(new_img[:, :, 2], 0.3, img_saturation, 0.7, 0)
Put important constants like this at the top of the file

2024-06-09 19:02 UTC, eblake003 commented on vision/standard_object/odlc_contour_detection.py
> +    new_img = cv2.GaussianBlur(new_img, (5, 5), sigmaX=0, sigmaY=0)  # blurs HLS image
Put `KERNEL_SIZE = (5, 5)` at the top

2024-06-09 19:02 UTC, eblake003 commented on vision/standard_object/odlc_contour_detection.py
> +    img = cv2.imread(filename)
`img` should be an argument to the function instead of being read from a file

2024-06-09 19:02 UTC, eblake003 commented on vision/standard_object/odlc_contour_detection.py
> +    img = cv2.imread(filename)
typehint with the `Image` typealias from `vision.common.constants`

2024-06-10 03:01 UTC, Ooglely commented on vision/standard_object/odlc_contour_detection.py
> +    if draw_contours:
I think it would be fine to keep. It would be useful for unit tests and it doesn't activate unless the test argument is passed

2024-06-15 16:51 UTC, EnderDude67 requested changes
Looks good and sounds like it's working, so I don't have any major problems. Just some small changes to things like documentation and typehints.

2024-06-15 16:51 UTC, EnderDude67 commented on vision/standard_object/odlc_text_detection.py
>      Detects text in the passed image at the location specified by the passed bounding box.
Update documentation to reflect removal of bounding box parameter

2024-06-15 16:51 UTC, EnderDude67 commented on vision/pipeline/standard_pipeline.py
> -    contour_heirarchies_list: ContourHeirarchyList = iterate_find_contours(original_image)
`iterate_find_contours()` should be deleted now that it is no longer in use

2024-06-15 16:51 UTC, EnderDude67 commented on vision/standard_object/odlc_colors.py
> +    print(find_colors(img))
remove print statement if it is not needed or helpful

2024-06-15 16:51 UTC, EnderDude67 commented on vision/standard_object/odlc_contour_detection.py
> +        _x_pos, _y_pos, width, height = cv2.boundingRect(contour)
typehints needed

2024-06-15 16:51 UTC, EnderDude67 commented on vision/standard_object/odlc_contour_detection.py
> +    img_brightness: np.ndarray[np.dtype[np.uint8], np.dtype[np.uint8]]
use `ScImage` typealias from `vision.common.constants`

2024-06-15 16:51 UTC, EnderDude67 commented on vision/standard_object/odlc_contour_detection.py
> +    img = cv2.cvtColor(image, cv2.COLOR_RGB2HLS)  # converts image to HLS color format
rename to `hls_img` for clarity

2024-06-15 16:51 UTC, EnderDude67 commented on vision/standard_object/odlc_contour_detection.py
> +    saturation_value: int = MIN_SATURATION_VALUE if avg_brt > 60 else MIN_DARK_SATURATION_VALUE
make constant `BRIGHTNESS_THRESH = 60`

2024-06-18 15:05 UTC, EnderDude67 requested changes
Just a few more changes. Once these are fixed it will be ready

2024-06-18 15:05 UTC, eblake003 commented on vision/standard_object/odlc_contour_detection.py
> +    white_thresh: np.ndarray[np.dtype[np.uint8], np.dtype[np.uint8]]
If this matches the `Mask` typealias from `vision.common.constants`, then it should be used. If not, it should probably be changed to the same format with shape typing

2024-06-18 15:05 UTC, eblake003 commented on vision/standard_object/odlc_contour_detection.py
> +        proportional_area = area / (width * height)
typehint

2024-06-18 15:05 UTC, eblake003 commented on vision/standard_object/odlc_contour_detection.py
> +        area = float(cv2.contourArea(contour))
typehint

2024-06-18 15:05 UTC, eblake003 commented on vision/standard_object/odlc_contour_detection.py
> +        aspect_ratio = max(float(width) / height, float(height) / width)
typehint

2024-06-18 15:05 UTC, eblake003 commented on vision/standard_object/odlc_contour_detection.py
> +        solidity = area / (cv2.contourArea(cv2.convexHull(contour)))
typehint

2024-06-18 15:05 UTC, eblake003 commented on vision/standard_object/odlc_contour_detection.py
> +    hls_img = cv2.cvtColor(image, cv2.COLOR_RGB2HLS)  # converts image to HLS color format
Typehint as `Image`

2024-06-18 15:05 UTC, eblake003 commented on vision/standard_object/odlc_contour_detection.py
> +    new_img = cv2.GaussianBlur(hls_img, KERNEL_SIZE, sigmaX=0, sigmaY=0)  # blurs HLS image
rename to `hls_blurred` or something similar

2024-06-18 15:05 UTC, eblake003 commented on vision/standard_object/odlc_contour_detection.py
> +    for contour in contours:
typehint `contour`

2024-06-18 15:05 UTC, eblake003 commented on vision/standard_object/odlc_contour_detection.py
> +    filename : str
update documentation to reflect new parameters

2024-06-18 15:05 UTC, eblake003 commented on vision/standard_object/odlc_contour_detection.py
> +    img_brightness = np.array(new_img[:, :, 1])  # reads lightness of image as 2D array
rename both to `blurred_brightness` and `blurred_saturation` or something similar

2024-06-18 15:05 UTC, eblake003 commented on vision/standard_object/odlc_contour_detection.py
> +    saturation_thresh: np.ndarray[np.dtype[np.uint8], np.dtype[np.uint8]]
update these two as well

2024-06-18 15:05 UTC, eblake003 commented on vision/standard_object/odlc_contour_detection.py
> +    saturation_value: int = (
move this above the typehints for `white_thresh` and `black_thresh`

2024-06-18 15:05 UTC, EnderDude67 commented on vision/standard_object/odlc_contour_detection.py
> +    white_thresh = cv2.dilate(white_thresh, np.ones([3, 3], np.uint8))
make new constant `DILATION_KERNEL: NDArray[Shape["3, 3"], UInt8] = np.ones([3, 3], np.uint8)` and use it in all three of these

2024-06-18 15:08 UTC, EnderDude67 commented on vision/standard_object/odlc_contour_detection.py
> +    white_thresh: np.ndarray[np.dtype[np.uint8], np.dtype[np.uint8]]
It seems like comments are displayed in the order that I made them, not the order that they appear in the file. Hopefully it's not too annoying that they will be kind of randomly shuffled

2024-06-19 02:18 UTC, EnderDude67 requested changes

2024-06-19 02:18 UTC, EnderDude67 commented on vision/standard_object/odlc_contour_detection.py
> +    white_thresh = DILATION_KERNEL
`DILATION_KERNEL` only replaces the `np.ones(...)`, so:

```suggestion
    white_thresh = cv2.dilate(white_thresh, DILATION_KERNEL)
```

2024-06-19 02:18 UTC, EnderDude67 commented on vision/standard_object/odlc_contour_detection.py
> +    black_thresh = DILATION_KERNEL
```suggestion
    black_thresh = cv2.dilate(black_thresh, DILATION_KERNEL)
```

2024-06-19 02:18 UTC, EnderDude67 commented on vision/standard_object/odlc_contour_detection.py
> +    saturation_thresh = DILATION_KERNEL
```suggestion
    saturation_thresh = cv2.dilate(saturation_thresh, DILATION_KERNEL)
```

2024-06-19 02:31 UTC, EnderDude67 approved these changes

2024-06-19 18:00 UTC, merged