Emergent Object Detection/Classification Model.v1
MissouriMRR/SUAS-2023 pull request #56
Opened 2023-02-22 00:57 UTC by knowabee

Closes #12 
Model to detect / classify emergent objects & pretrained weights for the model.

2023-02-22 01:20 UTC, fallscameron01 requested changes
Need a few changes to make sure the code is up to repo standards. You can check out the comments below for specifics. In addition to those comments, a few more changes below:

- Might want to choose a better name for `best.pt`. Something like `emergent_model.pt` or weights or something
- Make sure that your code is passing pre-commit checks for mypy and pylint. You can check how to install/use these in the `ReadMe.md`

2023-02-22 01:20 UTC, fallscameron01 commented on vision/emergent_object/emergent_object.py
> +import pandas
These will have to be added to `pyproject.toml` file as dependencies.

2023-02-22 01:20 UTC, fallscameron01 commented on vision/emergent_object/emergent_object.py
> +def emergent_object_model(path_to_weights):
Instead of a comment, should be using a docstring: https://missourimrr.github.io/docs/python/documenting-code/docstrings/#docstrings

2023-02-22 01:20 UTC, fallscameron01 commented on vision/emergent_object/emergent_object.py
> +def emergent_object_model(path_to_weights):
Also, will need to add type hints for parameter/return types: https://missourimrr.github.io/docs/python/type-annotations/full-guide.html

2023-02-22 01:20 UTC, fallscameron01 commented on vision/emergent_object/emergent_object.py
> +def emergent_object_model(path_to_weights):
Better name for this function might be `create_emergent_model()`

2023-02-22 01:20 UTC, fallscameron01 commented on vision/emergent_object/emergent_object.py
> +def emergent_object_model(path_to_weights):
Should have the path to your file as a default for the `path_to_weights` parameter

2023-02-22 01:20 UTC, fallscameron01 commented on vision/emergent_object/emergent_object.py
> +    )  # path depends on location of the pretrained weights
Need a type hint for `model`

2023-02-22 01:20 UTC, fallscameron01 commented on vision/emergent_object/emergent_object.py
> +    )  # path depends on location of the pretrained weights
This comment isn't necessary

2023-02-22 01:20 UTC, fallscameron01 commented on vision/emergent_object/emergent_object.py
> +def emergent_object_detection(image_path, model):
Same thing for this function, need type hints and a docstring

2023-02-22 01:20 UTC, fallscameron01 commented on vision/emergent_object/emergent_object.py
> +    output = results.pandas().xyxy[0]
Need type hints for `image`, `results`, and `output`.

2023-02-22 01:20 UTC, fallscameron01 commented on vision/emergent_object/emergent_object.py
> +    output = results.pandas().xyxy[0]
`results` and `output` aren't very descriptive variable names

2023-02-22 01:20 UTC, fallscameron01 commented on vision/emergent_object/emergent_object.py
> +    return output
A comment describing the format of `output` would be helpful

2023-02-22 01:20 UTC, fallscameron01 commented on vision/emergent_object/emergent_object.py
> +    emergent_object_detection()
For your main, you should make it so that it would run properly by adding parameters for these functions. Also would be good to print the output.

2023-02-22 01:20 UTC, fallscameron01 commented on vision/emergent_object/emergent_object.py
> +def emergent_object_detection(image_path, model):
Better name would be `detect_emergent_object()`

2023-02-27 22:20 UTC, fallscameron01 commented on vision/emergent_object/emergent_object.py
> +import pandas
Fixed by #58

2023-03-02 20:31 UTC, fallscameron01 commented
Good first issue for someone to take up the fixes for this PR

2023-03-04 22:53 UTC, EnderDude67 commented
I worked out how to use the model and the output and added some code demonstrating its use. Docstrings and proper typehinting still need to be added, but the functionality should be pretty much all there at this point.

2023-03-06 05:21 UTC, fallscameron01 requested changes
Updated review to reflect @EnderDude67 's changes. Comments from old review may be out of date, so refer to this review first and foremost.

2023-03-06 05:21 UTC, fallscameron01 commented on vision/emergent_object/emergent_object.py
> +#   seaborn
Dependencies should all be taken care of by #58 if you run in a poetry shell. These comments can be removed.

2023-03-06 05:21 UTC, fallscameron01 commented on vision/emergent_object/emergent_object.py
> +MODEL_PATH = "vision/emergent_object/best.pt"
Since this constant is only used in `emergent_object_model()`, constant `MODEL_PATH` should be moved to that function.

2023-03-06 05:21 UTC, fallscameron01 commented on vision/emergent_object/emergent_object.py
> +    return output
Function needs:
- docstring
- parameter types
- return type

2023-03-06 05:21 UTC, fallscameron01 commented on vision/emergent_object/emergent_object.py
> +    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
Type hint for `image` should be `Image` type alias from vision > common > constants.py

2023-03-06 05:21 UTC, fallscameron01 commented on vision/emergent_object/emergent_object.py
> +    output = results.pandas().xyxy[0]
type hints for results and output

2023-03-06 05:21 UTC, fallscameron01 commented on vision/emergent_object/emergent_object.py
> +    output = results.pandas().xyxy[0]
`results` and `output` aren't very descriptive variable names

2023-03-06 05:21 UTC, fallscameron01 commented on vision/emergent_object/emergent_object.py
> +    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
Instead of assigning the result of `cv2.cvtColor` to the parameter `image`, assign it to a new variable (i.e. `image_rgb`)

2023-03-06 05:21 UTC, fallscameron01 commented on vision/emergent_object/emergent_object.py
> +    return model
Function needs:
- docstring
- return type

2023-03-06 05:21 UTC, fallscameron01 commented on vision/emergent_object/emergent_object.py
> +    return model
need type hint for `model`

2023-03-06 05:21 UTC, fallscameron01 commented on vision/emergent_object/emergent_object.py
> +
`cv2` import should be at the top of the file since it is used in `emergent_object_detection()`

2023-03-06 05:21 UTC, fallscameron01 commented on vision/emergent_object/emergent_object.py
> +
Could make this into a command line argument

2023-03-06 05:21 UTC, fallscameron01 commented on vision/emergent_object/emergent_object.py
> +    output = emergent_object_detection(image, model)
Type hints for `image`, `model`, `output`.

2023-03-06 05:21 UTC, fallscameron01 commented on vision/emergent_object/emergent_object.py
> +    output = emergent_object_detection(image, model)
`output` isn't a very descriptive variable name

2023-03-06 05:21 UTC, fallscameron01 commented on vision/emergent_object/emergent_object.py
> +    output_dict = output.to_dict("index")
Should do what this comment says about the `emergent_object_detection` function

2023-03-06 05:21 UTC, fallscameron01 commented on vision/emergent_object/emergent_object.py
> +    output_dict = output.to_dict("index")
type hint for `output_dict`

2023-03-06 05:21 UTC, fallscameron01 commented on vision/emergent_object/emergent_object.py
> +    for row in output_dict.values():
Type hint for `row`. Loop variables are type hinted like this:

```
row: Type
for row ...
```

2023-03-06 05:21 UTC, fallscameron01 commented on vision/emergent_object/emergent_object.py
> +        bottom_right = (int(row["xmax"]), int(row["ymax"]))
type hints for these two variables

2023-03-06 05:21 UTC, fallscameron01 commented on vision/emergent_object/emergent_object.py
> +    cv2.imshow("", image)
Might want something like "Emergent Object" instead of an empty string for the title.

2023-03-06 05:21 UTC, fallscameron01 commented on vision/emergent_object/emergent_object.py
> +    return output
For the docstring for this function, make sure to describe what kind of output one should expect from it.

2023-03-12 01:37 UTC, fallscameron01 commented
Opened new PR #96 because something was wrong with this branch that caused a split.

2023-03-12 01:37 UTC, closed without merging