Waypoint Flight State
MissouriMRR/SUAS-2023 pull request #84
Opened 2023-03-08 01:58 UTC by DJDMVP

Flight state for drone moving through each of the waypoints.

2023-03-09 18:22 UTC, fallscameron01 commented
Change title to something better and add a description

2023-03-10 01:36 UTC, cjhr95 requested changes
Documentation

2023-03-10 01:36 UTC, cjhr95 commented on flight/extract_gps.py
> +        return self
Docstring here plz

2023-03-10 01:36 UTC, cjhr95 commented on flight/extract_gps.py
> +        raise StopAsyncIteration
Docstring here again

2023-03-10 01:36 UTC, cjhr95 commented on flight/states/waypoints.py
> +            await move_to(drone, waypoint[0], waypoint[1], waypoint[2], 2 / 3)
Add a comment here explaining my 2/3 is the float you use for the fast_param

2023-03-10 02:01 UTC, cjhr95 approved these changes
Seems alright I GUESS.

2023-03-14 23:13 UTC, cjhr95 approved these changes
Seems alright

2023-03-14 23:15 UTC, merged