feature/odlc-classify-shape
MissouriMRR/SUAS-2023 pull request #85
Opened 2023-03-08 02:10 UTC by OrangePear13

#closes #52

Evan made me mess up my old branch so I made a new one with all of the changes. has all of the shape classification logic complete and modified `odlc_contour_filtering.py`

New code in `vision/standard_object/odlc_classify_shape.py`
Takes in a shape, runs the contour filtering and classifies the odlc shape

2023-03-08 03:04 UTC, fallscameron01 requested changes
Need a few changes. Mostly formatting and some variable name changes.

Also, TIL match case was a thing.

2023-03-08 03:04 UTC, fallscameron01 commented on vision/standard_object/odlc_classify_shape.py
> +    # print(type(convex_hull), convex_hull.shape, convex_hull)
Remove comment

2023-03-08 03:04 UTC, fallscameron01 commented on vision/standard_object/odlc_classify_shape.py
> +    # print(type(defects), defects.shape, defects)
Remove comment

2023-03-08 03:04 UTC, fallscameron01 commented on vision/standard_object/odlc_classify_shape.py
> +    )
A couple of comments about what these do would be helpful

2023-03-08 03:04 UTC, fallscameron01 commented on vision/standard_object/odlc_classify_shape.py
> +            The other point that forms the angle, 2nd index in the tuple.
Also need a line about `pts` in general, which would go right above the `pt_a` line and will be indented

2023-03-08 03:04 UTC, fallscameron01 commented on vision/standard_object/odlc_classify_shape.py
> +        The angle (in deg) of the angle formed by the lines (pt_a, vertex) and (vertex, pt_c)
`pt_c` or `pt_b` ?

2023-03-08 03:04 UTC, fallscameron01 commented on vision/standard_object/odlc_classify_shape.py
> +    )
Might be more clear if you split this up a little rather than having one massive statement. For example, you do `pts[0] - pts[1]` and `pts[2] - pts[1]` twice each, so these could be variables.

2023-03-08 03:04 UTC, fallscameron01 commented on vision/standard_object/odlc_classify_shape.py
> +        angles[idx] = get_angle((approx[idx - 1], a_pt, approx[(idx + 1) % approx.shape[0]]))
Need type hints for `idx` and `a_pt`

2023-03-08 03:04 UTC, fallscameron01 commented on vision/standard_object/odlc_classify_shape.py
> +        The value to compare each element of angles to.
Better name might be `compare_angle` or something similar, rather than having the parameters `angles` and `angle`

2023-03-08 03:04 UTC, fallscameron01 commented on vision/standard_object/odlc_classify_shape.py
> +        are_valid[idx] = -thresh < elem - angle < thresh
type hints for `idx` and `elem`. Also, `elem` isn't a very descriptive variable name

2023-03-08 03:04 UTC, fallscameron01 commented on vision/standard_object/odlc_classify_shape.py
> +        )
type hints for `idx` and `a_pt`

2023-03-08 03:04 UTC, fallscameron01 commented on vision/standard_object/odlc_classify_shape.py
> +                lengths = get_lengths(approx)
Type hint for `lengths`

2023-03-08 03:04 UTC, fallscameron01 commented on vision/standard_object/odlc_classify_shape.py
> +    Alternative
Alternative? Not sure what this is referring to.

2023-03-08 03:04 UTC, fallscameron01 commented on vision/standard_object/odlc_classify_shape.py
> +    if abs((max_dist / perimeter) - 0.388) < 0.1:
Magic numbers should be constants here for clarity. `0.280`, `0.388`, and `0.1`

2023-03-08 03:04 UTC, fallscameron01 commented on vision/standard_object/odlc_classify_shape.py
> +        Will return one of the ODLC shapes defined in vision/common/odlc_characteristics or None
When does it return `None`? Should specify here

2023-03-08 03:04 UTC, fallscameron01 commented on vision/standard_object/odlc_classify_shape.py
> +        shape = classify_circular(contours[index])
Feels like this is a bit backwards. Since the variable name is `is_circular`, you should check that first and the not circular would be the else. Doing a `not` operation for no reason.

2023-03-08 03:04 UTC, fallscameron01 commented on vision/standard_object/odlc_contour_filtering.py
> +# in test_roughness()
Break this up a bit with some newlines between the constants

2023-03-08 03:04 UTC, fallscameron01 commented on vision/standard_object/odlc_classify_shape.py
> +# epsilon is the max distance between the approximation's and the original's curves
Same thing about breaking up the constants with newlines in the other file

2023-03-08 03:04 UTC, fallscameron01 commented on vision/standard_object/odlc_contour_filtering.py
> +    mask = cv2.drawContours(mask, [shifted_cnt], -1, True, cv2.FILLED).astype(Bool8)
`Mask` as defined in the constants file is `Bool`, not `Bool8`. If the intention is to switch to `Bool8`, then you should change the `Mask` type alias. Otherwise this type hint is wrong.

2023-03-08 03:04 UTC, fallscameron01 commented on vision/standard_object/odlc_contour_filtering.py
> +    docs.opencv.org/4.x/dd/d1a/group__imgproc__feature.html#ga47849c3be0d0406ad3ca45db65a25d2d
Don't need the comment about the https

2023-03-08 03:04 UTC, fallscameron01 commented on vision/standard_object/odlc_contour_filtering.py
> +    modded = cv2.GaussianBlur(img, (7, 7), 1.5)
might make this more clear
```suggestion

    modded = cv2.GaussianBlur(img, ksize=(7, 7), sigmaX=1.5)
```

2023-03-08 03:04 UTC, fallscameron01 commented on vision/standard_object/odlc_contour_filtering.py
> +    test_image1 = cv2.circle(test_image1, (249, 249), 245, (255, 255, 255))
Commented line can be removed

2023-03-08 23:53 UTC, EnderDude67 requested changes
Looks good! Just requesting a few changes to improve usability for me. Consider reordering your functions from highest level to lowest level to help me follow the flow of your code.

2023-03-08 23:53 UTC, EnderDude67 commented on vision/standard_object/odlc_classify_shape.py
> +if __name__ == "__main__":
Add a demonstration of `classify_shape`

2023-03-08 23:53 UTC, EnderDude67 commented on vision/standard_object/odlc_classify_shape.py
> +) -> chars.ODLCShape | None:
Add a function that takes in the contours and hierarchy and loops through them all and returns an array of `BoundingBoxes` with the shape as an object attribute

2023-03-09 00:09 UTC, fallscameron01 requested changes
Few more changes

2023-03-09 00:09 UTC, fallscameron01 commented on vision/standard_object/odlc_classify_shape.py
> +            The other point that forms the angle, 2nd index in the tuple.
The comment on 91 about the point format should be in the general description of the `pts` parameter, not under `pt_a`

2023-03-09 00:09 UTC, fallscameron01 commented on vision/standard_object/odlc_classify_shape.py
> +                    shape = chars.ODLCShape.SQUARE
Add a couple of comments about what these are checking for

2023-03-09 00:09 UTC, fallscameron01 commented on vision/standard_object/odlc_classify_shape.py
> +) -> chars.ODLCShape | None:
As Evan said, you should add a function that returns a `BoundingBox` object for the detected shape(s) with the `ODLCShape` as one of its `attributes`.

2023-03-11 21:04 UTC, fallscameron01 requested changes
One small formatting change and then you're good to go.

2023-03-11 21:04 UTC, fallscameron01 commented on vision/standard_object/odlc_classify_shape.py
> +            Image width.
Remove extra newlines between parameters.

2023-03-11 23:11 UTC, OrangePear13 commented
The function reordering in the last commit was asked for by @EnderDude67 to improve ease of use when making the vision pipeline.

2023-03-11 23:33 UTC, fallscameron01 approved these changes
Nice work, ready for merge.

2023-03-12 00:34 UTC, EnderDude67 approved these changes

2023-03-12 00:41 UTC, merged