Takeoff State Logic
MissouriMRR/SUAS-2023 pull request #87
Opened 2023-03-10 01:08 UTC by carson-williams

2023-03-10 01:17 UTC, cjhr95 requested changes
Just a small thing about the takeoff altitude.

2023-03-10 01:17 UTC, cjhr95 commented on flight/states/takeoff.py
> +        await drone.action.set_takeoff_altitude(75 / 3.2808)
Here I would import the constant TAKEOFF_ALT from the config.py file here, so it doesn't seem like this value is appearing out of thin air.

2023-03-14 23:33 UTC, cjhr95 approved these changes
Looks good!

2023-04-04 23:56 UTC, fallscameron01 commented
If this is good to merge, you can go ahead and do that @cjhr95

2023-04-05 17:59 UTC, merged