Air Drop Mechanism Control and Maestro Class
MissouriMRR/SUAS-2023 pull request #89
Opened 2023-03-10 01:22 UTC by Ooglely

Creates a Maestro class in order to be able to control the servos that will be on the boards, and uses it to run the functions to use the air drop mechanism.

2023-03-10 01:39 UTC, Ooglely commented
Waiting on a working power cable so that I can test the class functions.

2023-03-21 23:55 UTC, fallscameron01 requested changes
Few changes to make, mostly around documentation and type hints.

2023-03-21 23:55 UTC, fallscameron01 commented on flight/maestro/air_drop.py
> +import maestro
Imports should be relative to root

2023-03-21 23:55 UTC, fallscameron01 commented on flight/maestro/air_drop.py
> +BOARD: maestro.Maestro = maestro.Maestro()
Don't think this should be a constant. Alternative would be to create a class that encompasses this and the other functions in this file.

2023-03-21 23:55 UTC, fallscameron01 commented on flight/maestro/maestro.py
> +        A list of the current targets for each channel.
Shouldn't have extra newlines between these.
```suggestion
    serial: serial.Serial
        Serial object to be able to read and send messages to and from the board.
    command_prefix: str
        The command protocol prefix that is sent before every command to the board.
    targets: list(int)
        A list of the current targets for each channel.
```

2023-03-21 23:55 UTC, fallscameron01 commented on flight/maestro/maestro.py
> +    -------
Same thing for your methods

2023-03-21 23:55 UTC, fallscameron01 commented on flight/maestro/maestro.py
> +        ----------
And in all the other docstrings

2023-03-21 23:55 UTC, fallscameron01 commented on flight/maestro/maestro.py
> +            The rate of communication configured for the board (default 9600)
State the defaults for these in the docstring

2023-03-21 23:55 UTC, fallscameron01 commented on flight/maestro/maestro.py
> +        msb = ord(self.serial.read())
Type hints for these 2

2023-03-21 23:55 UTC, fallscameron01 commented on flight/maestro/maestro.py
> +        low, high = self._get_bits(target)
Type hints for theses 2 variables.

2023-03-21 23:55 UTC, fallscameron01 commented on flight/maestro/maestro.py
> +
And this one needs a type hint as well

2023-03-21 23:55 UTC, fallscameron01 commented on flight/maestro/maestro.py
> +        low, high = self._get_bits(speed)
Type hints

2023-03-21 23:55 UTC, fallscameron01 commented on flight/maestro/maestro.py
> +        command = chr(0x07) + chr(channel) + chr(low) + chr(high)
Type hint

2023-03-21 23:55 UTC, fallscameron01 commented on flight/maestro/maestro.py
> +        command = chr(0x09) + chr(channel) + chr(low) + chr(high)
And here

2023-03-21 23:55 UTC, fallscameron01 commented on flight/maestro/maestro.py
> +        result = self._read_bits()
Type hints for `command` and `result`

2023-03-21 23:55 UTC, fallscameron01 commented on flight/maestro/maestro.py
> +        return result
Shouldn't be printing

2023-03-21 23:55 UTC, fallscameron01 commented on flight/maestro/maestro.py
> +        response = self.serial.read()
Type hint for `response`

2023-03-21 23:55 UTC, fallscameron01 commented on flight/maestro/maestro.py
> +            True if servos are still moving, false if not
```suggestion
        response: bool
            True if servos are still moving, False if not
```

2023-03-21 23:55 UTC, fallscameron01 commented on flight/maestro/maestro.py
> +        result = self._read_bits()
Type hint for `result`

2023-03-21 23:55 UTC, fallscameron01 commented on flight/maestro/maestro.py
> +        return result
remove print statement

2023-03-22 00:36 UTC, cjhr95 requested changes
I don't believe the functions should be async, it might mess up the servo functionality, just when they're called in the state we can run it asynchronously.

2023-03-22 00:36 UTC, cjhr95 commented on flight/maestro/air_drop.py
> +BOARD: maestro.Maestro = maestro.Maestro()
Another alternative would be to pass a Maestro class into each function, similar to the drone object we pass for flight stuff

2023-03-22 00:36 UTC, cjhr95 commented on flight/maestro/maestro.py
> +    targets: list(int)
type hint for the list should be `targets: list[int]`

2023-03-22 00:36 UTC, cjhr95 commented on flight/maestro/maestro.py
> +        See: https://www.pololu.com/docs/0J40/5.e
Throw this link into a separate "Notes" section in your docstring

2023-03-22 00:53 UTC, cjhr95 submitted a review, later dismissed
Seems solid to me

2023-03-22 00:54 UTC, fallscameron01 requested changes
Couple of docstring issues

2023-03-22 00:54 UTC, fallscameron01 commented on flight/maestro/maestro.py
> +        return result
The return variable is `result`

2023-03-22 00:54 UTC, fallscameron01 commented on flight/maestro/maestro.py
> +        return result
Same here

2023-03-22 00:57 UTC, fallscameron01 approved these changes
Looks good

2023-03-22 00:58 UTC, cjhr95 approved these changes
Kinda rude to dismiss my review but whatever

2023-03-22 00:59 UTC, merged